name: Lint, Test and Deploy the Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint # Ensure you have a lint script in package.json

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: build artifact
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: artifact
            path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
            name: artifact
      - name: Output Content
        run: ls -lah
      - name: Deploy the app
        run: echo "App is being deployed..."
