name: Output Github Context
on:
  issues:
    types: [opened, edited, closed]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub Context
        run: echo "${{ toJson(github) }}"

      - name: Output Event Name
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
